name: Context Variables
on:
  workflow_dispatch:
env:
  cloud: google_cloud
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
    - name: "Checking Context Variables"
      run: |
        echo "Repository Name : ${{ github.repository }}"
        echo "Workflow Name : ${{ github.workflow }}"
        echo "Triggered by : ${{ github.triggering_actor }}"
      env:
        First_name: VG
