name: Secret Variables
on:
  workflow_dispatch:
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
    - name: "Checking Secret Variables"
      run: |
        echo "Secret Variable : ${{ secrets.TEST_KEY }}"
        ${{ secrets.TEST_KEY }}
